### ISSUE TITLE
Is this different to https://github.com/jfairbank/combos#combos?

### ISSUE THREAD

**Issue by rwalle61** [nas5w/combinate#3]
Hi, thanks for this and your article https://typeofnan.dev/generate-all-possible-combinations-in-javascript-using-combinate/ !

This package is perfect for my problem. However, I also found another older package that seems to do the same thing: https://github.com/jfairbank/combos#combos.

So I was wondering if there's a difference between these 2 packages that I haven't noticed?

Thanks again :)

**Comment by nas5w** [comment]
It looks like it's not! I had not seen `combos` before. I'm actively maintaining `combinate` though, whereas `combos` seems to have been dormant for four years.
